### ISSUE TITLE
the alternate file

### ISSUE THREAD

**Issue by gfixler** [dhruvasagar/vim-vinegar#2]
Would it be possible for vinegar to keep NERDTree windows out of the jump list? I'd like `<C-o>` and `<C-^>` to skip over NERDTree windows opened with vinegar. When I navigate to a new file, and jump back, I end up back in NERDTree, but I always want to be back in the previous file. I can get back to NERDTree with a simple `-`, after all.

**Comment by Frydac** [comment]
Hi, too bad this is still an issue, and probably the reason why I won't be using this plugin.

For ppl encountering this issue, and thinking the same,  the following is good enough for me (for now at least..):
I just map `-` as follows:
`nnoremap - :NERDTreeFind<cr>`
which opens NERDtree in its own window with the cursor on the current buffers file, and doesn't affect the jumplist or alternate file.
And using the setting that will close the NERDTree window after opening a file:
`let g:NERDTreeQuitOnOpen=1`
This way, NERDTree works seamless with multiple split windows: pressing `-` from a split will jump to the NERDTree window, when opening a file the cursor will jump back to the correct split and the NERDTree window will be closed.
The experience is not the same, but works a little more intuitive than my previous mappings.
Then I use following standard NERDTree mappings, for example:
`u` to go up one folder when in flat folder or in root, or `p` when you are in a subtree
`cd` to change the CWD to the currently selected file/dir
Could use bookmarks for the home folder I guess, but I don't use those.
Also, the current buffers' filename is stored in register `%`, so when on command line (or in insert mode), `<Ctrl-r>%` will insert that filename.

**Comment by dhruvasagar** [comment]
Actually I myself have stopped using this plugin, NERDTree and tpope/vim-vinegar myself.

I use this now : 
```viml
function! s:vinegar()
  let fname = expand('%:t')
  edit %:h
  normal! gg
  call search('\<'.fname.'\>')
endfunction
nnoremap - :<C-U>call <SID>vinegar()<CR>
```

Edit: That should also work fairly well with nerdtree from what I can tell
