### ISSUE TITLE
Catching up with tpope/vim-vinegar

### ISSUE THREAD

**Issue by amacfie** [dhruvasagar/vim-vinegar#3]
Great fork I use it all the time! I just wanted to remark that the repo is currently 16 commits behind `tpope/vim-vinegar` and some of the changes are useful so they should be merged in.

**Comment by dhruvasagar** [comment]
True, u tried sometime back but it was hard to resolve conflicts, I'll give
it another try.

**Comment by dhruvasagar** [comment]
I have pushed some updates which are in-line with tpope/vim-vinegar that aren't netrw related.
