### ISSUE TITLE
No tie between vim-vinegar and NERDTree

### ISSUE THREAD

**Issue by gfixler** [dhruvasagar/vim-vinegar#4]
I started to track down why the latest in both repos puts me in a state wherein seeking to the file when pressing `-` doesn't work (the cursor stays at the top of the listing), and I realized that there's really no tie between these two repos. I'm currently at bcf3de4 in NERDTree, and on 1d69b86 on master in vim-vinegar. If I switch to vim-vinegar to the current tpope branch head at 923490c, then seeking works, and if I swap out this fork for tpope's original, it also works. I see the tpope branch is more than  year old, though. Checking out one commit back on master, to 462edb3, I see it works again, so perhaps I can sum this up by saying that it seems the latest commit on master in this repo breaks file-seeking, and asking how I'm to know which NERDTree to use with each commit in this fork of vim-vinegar?

**Comment by dhruvasagar** [comment]
You should just be using the latest NERDTree, I made a change recently in trying to merge recent changes from tpope's updates. I'll have another look tonight and will let you know once I have fixed the issue.

**Comment by jfouk** [comment]
Hi, I'm updated to the latest NERDTree and vim-vinegar and I have the same issue; - opens up NERDTree and puts the cursor at the top of the screen instead of seeking the current file. Any updates on this?

**Comment by dhruvasagar** [comment]
hmm, ok sorry for this, i'll check it out and fix it

**Comment by gfixler** [comment]
I have a 1-line fix for `plugin/vinegar.vim`, line 37 against commit 1d69b86.

    let pattern = '^ *\%(▸ \)\?'.escape(a:file, '.*[]~\').'\>'

I could make it a pull request if you like. It works for me across all the files and folders (and nested folders) that I've tried.

**Comment by dhruvasagar** [comment]
That would be great!
